DaeguBus_System/DaeguBus_System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservation/', include('reservation.urls')),
]

DaeguBus_System/reservation/urls.py
from re import template
from django.urls import path 
from . import views 
from django.contrib.auth import views as auth_views

app_name = 'reservation'

urlpatterns = [ 
    path('' , views.index, name='main'),
    path('login/', auth_views.LoginView.as_view(
         template_name='reservation/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('join/', views.CreatUser, name='CreatUser'),
    path('reserve/', views.BusWatch, name='ReserveSeat'),
]

DaeguBus_System/reservation/models.py
from csv import unregister_dialect
from secrets import choice
# from django.db import models
from djongo import models
import pymongo

client = pymongo.MongoClient("mongodb+srv://dbUser:1234@cluster0.3fk5bkx.mongodb.net/?retryWrites=true&w=majority")
db = client.deagu_bus
col_user = db.user_info

# Create your models here.
class User_db(models.Model):
    NATIONAL_CHOICES = (
        ('NP', 'Nomal person'),
        ('WP','Weak person'),
    )
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    type = models.CharField(max_length=2, choices=NATIONAL_CHOICES)

    def __str__(self):
        return self.user_id

class ReserveBus(models.Model):
    BUS_CHOICES = (
        ('N1', '예약버스 1번'),
        ('N2', '예약버스 2번'),
        ('N3', '예약버스 3번'),
    )

    busname = models.CharField(max_length=2, choices=BUS_CHOICES)
    startStation = models.CharField(max_length=200)
    endStation = models.CharField(max_length=200)

    def __str__(self):
        return self.user_id

DaeguBus_System/reservation/forms.py
from django import forms
from reservation.models import User_db, ReserveBus
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User_db
        fields = ['username', 'password', 'type']
        labels = {
            'username': '아이디',
            'password': '비밀번호',
            'type': '사용자 유형',
        }

class BusResrveForm(forms.ModelForm):
    class Meta:
        model = ReserveBus
        fields = ['busname', 'startStation', 'endStation']
        labels = {
            'busname': '버스 이름',
            'startStation': '출발지',
            'endStation': '도착지',
        }

DaeguBus_System/reservation/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
import user_info

from .forms import UserForm, BusResrveForm
from .models import ReserveBus, User_db

# Create your views here.
def index(request):
    return render(request, 'reservation/main.html')

def CreatUser(request):
    """
    회원가입
    """
    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user_info.add_user(user.username, user.password, user.type)

            return redirect('http://127.0.0.1:8000/reservation')
    else:
        form = UserForm()
    return render(request, 'reservation/join.html', {'form': form})


def BusWatch(request):
    """
    예약 버스 확인
    """
    if request.method == 'POST':
        form = BusResrveForm(request.POST)

        if form.is_valid():
            busname = form.busname
            return render(request, 'reservation/bus_watch.html', busname)
    else:
        form = BusResrveForm()
    return render(request, 'reservation/reserve.html')

DaeguBus_System/reservation/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

DaeguBus_System/reservation/templates/reservation/join.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>달려라, 달구벌</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme css (includes Bootstrap)-->
     <link rel="stylesheet" href="../../../static/styles.css">
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">달려라, 달구벌</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">버스정보조회</a></li>
                    <li class="nav-item"><a class="nav-link" href="/reservation/reser">버스선택</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">설정</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/reservation/help">도움말</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="/reservation/join">회원가입</a></li>
                            <li><a class="dropdown-item" href="/reservation/out">탈퇴하기</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <button class="btn btn-outline-dark" type="submit" href="/reservation/login">
                        <i class="bi-cart-fill me-1"></i>
                        <a href="login/">Login</a>
                        <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div id="wrap">
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">달려라, 달구벌</h1>
                    <p class="lead fw-normal text-white-50 mb-0">회원가입 페이지</p>
                </div>
            </div>
        </header>
        

        <section class="py-5">
            
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                        <div class="card h-100 mx-5 my-5">
                            <form method="post">
                                {% csrf_token %}
                                {% if form.errors %}
                                <div class="alert alert-danger" role="alert">
                                    {% for field in form %}
                                        {% if field.errors %}
                                        <strong>{{ field.label }}</strong>
                                        {{ field.errors }}
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                {% endif %}
                                
                                <div class="form-group"> 
                                    <label for="username">아이디</label> 
                                    <input type="text" class="form-control" name="username" id="username" 
                                            value="{{ form.username.value|default_if_none:'' }}"> 
                                </div> 
                                <div class="form-group"> 
                                    <label for="password">비밀번호</label> 
                                    <input type="text" class="form-control" name="password" id="password" 
                                            value="{{ form.password.value|default_if_none:'' }}">
                                </div>
                                <div class="form-group"> 
                                    <label for="type">사용자 유형</label> 
                                    <select class="form-control" name="type" id="type">
                                        {% for item in form.type %}   
                                            <option value="{{ item.id|default_if_none:'' }}">{{ item }}</option>  
                                        {% endfor %}
                                    </select>    
                                </div>
                                
                                <button type="submit">등록하기</button>
                            </form>
                        </div>
                
                </div>
            </div>
            

        </section>
    </div>
        
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy;2022 대구를 빛내는 SW해커톤 by.밥친구들</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
</body>
</html>

DaeguBus_System/reservation/templates/reservation/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>달려라, 달구벌</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme css (includes Bootstrap)-->
     <link rel="stylesheet" href="../../../static/styles.css">
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">달려라, 달구벌</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">버스정보조회</a></li>
                    <li class="nav-item"><a class="nav-link" href="/main/reser">버스선택</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">설정</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/main/help">도움말</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="/main/join">회원가입</a></li>
                            <li><a class="dropdown-item" href="/main/out">탈퇴하기</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <button class="btn btn-outline-dark" type="submit" href="/main/login">
                        <i class="bi-cart-fill me-1"></i>
                        <a href="login/">Login</a>
                        <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div id="wrap">
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">달려라, 달구벌</h1>
                    <p class="lead fw-normal text-white-50 mb-0">버스 예약 시스템</p>
                </div>
            </div>
        </header>
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-54">
                <div class="justify-content-center">
                    <div class="col mb-5">
                        <div class="card h-100">
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">등록하기</button>
                            </form>
                        </div>
                    </div>
                    
                </div>
                
            </div>
        </section>
    </div>
        
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy;2022 대구를 빛내는 SW해커톤 by.밥친구들</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
</body>
</html>

DaeguBus_System/reservation/templates/reservation/main.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
        <meta name="author" content="" />
        <title>달려라, 달구벌</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme css (includes Bootstrap)-->
         <link rel="stylesheet" href="../../../static/styles.css">
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">달려라, 달구벌</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'reservation:main' %}">버스정보조회</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'reservation:ReserveSeat' %}">버스선택</a></li> 
                </ul>
                <form class="d-flex">
                    <button class="btn btn-outline-dark" type="submit" href="login/">
                        <i class="bi-cart-fill me-1"></i>
                        {% if user.is_authenticated %}
                        <a href="{% url 'reservation:logout' %}">{{ user.usernmae }} (Logout) </a>
                        {% else %}
                        <a href="{% url 'reservation:login' %}">Login</a> 
                        {% endif %}
                        <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <div id="wrap">
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">달려라, 달구벌</h1>
                <p class="lead fw-normal text-white-50 mb-0">버스 예약 시스템</p>
            </div>
        </div>
    </header>

    <section class="py-5">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <div class="card h-100 mx-5 my-5">
                    <form method="post" class="post-form"> 
                        {% csrf_token %}
                        <div class="form-group">
                        <p>버스 정류장을 입력해주세요</p>
                        <input type="text" id="bus_station" name="bus_station">
                        </div>
                        <button type="submit" class="btn btn-primary">버스 정보 조회하기</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    </div>

    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy;2022 대구를 빛내는 SW해커톤 by.밥친구들</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
</body>
</html>

DaeguBus_System/reservation/templates/reservation/reserve.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
        <meta name="author" content="" />
        <title>달려라, 달구벌</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme css (includes Bootstrap)-->
         <link rel="stylesheet" href="../../../static/styles.css">
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">달려라, 달구벌</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'reservation:main' %}">버스정보조회</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'reservation:ReserveSeat' %}">버스선택</a></li> 
                </ul>
                <form class="d-flex">
                    <button class="btn btn-outline-dark" type="submit" href="login/">
                        <i class="bi-cart-fill me-1"></i>
                        {% if user.is_authenticated %}
                        <a href="{% url 'reservation:logout' %}">{{ user.usernmae }} (Logout) </a>
                        {% else %}
                        <a href="{% url 'reservation:login' %}">Login</a> 
                        {% endif %}
                        <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <div id="wrap">
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">달려라, 달구벌</h1>
                <p class="lead fw-normal text-white-50 mb-0">버스 예약 시스템</p>
            </div>
        </div>
    </header>

    <section class="py-5">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                
                    <strong>예약 버스 1번 노선</strong>
                    <ul>
                        <li>
                            봉무청구새들마을건너 -> 불로봉무파출소","위남마을","봉무초등학교건너","이시아폴리스더샵1단지","봉무공원건너","대구섬유박물관","불로동고분군건너","불로전통시장건너","불로화훼단지건너","불로삼거리","대구국제공항건너","공항시장건너","지저동행정복지센터건너","아양교3","아양교역(1번출구)","동구청앞","동구청역(4번출구)","산림조합중앙회건너","동대구역지하도1","동대구맨션","평화시장(닭똥집골목)앞","공고네거리1","강남약국건너","농협중앙회앞","칠성시장앞1"
                            425 : 동인치안센터건너","CGV대구한일건너","곽병원앞1","섬유회관건너1","큰장네거리1","대구제일고등학교건너","달서교회건너","KT서대구지사앞","서구청앞","신평리네거리2","평리청구타운앞","내당삼익맨션앞","두류역(달성고등학교앞)","감삼네거리1","서남시장앞1","구병원건너","죽전네거리2"
                            527: 죽전네거리2","용산네거리2","우방죽전타운앞1","용산1동행정복지센터앞","용산종합큰시장앞","2차서한화성타운앞","용산2동행정복지센터건너","성서청구타운앞","영남우방타운1차건너","조달청건너","동서화성타운앞","국민연금네거리1","성서우방타운앞","보성화성타운앞","와룡시장앞","성서종합시장건너","계명대학교동문앞","계명대역(1번출구)","계명대학교정문앞","계명대학교동산병원앞","강창역(1번출구)","삼성명가타운건너","강창교2","대실역청아람앞","대실역(1번출구)","다사고등학교앞","매곡사거리1","다사읍행정복지센터앞"
                        </li>
                    </ul>
                
            </div>
        </div>
    </section>

    <section class="py-5">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
 
                    <strong>예약 버스 2번 노선</strong>
                    <ul>
                        <li>여기</li>
                        <li>저기</li>
                    </ul>
                
            </div>
        </div>
    </section>

    <section class="py-5">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
               
                    <strong>예약 버스 3번 노선</strong>
                    <ul>
                        <li>뭐시기</li>
                    </ul>
            </div>
        </div>
    </section>

    <section class="py-5">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <form method="post" class="post-form"> 
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="form-group">
                        <label for="busname">버스 이름</label>
                        <select class="form-control" name="busname" id="busname">  
                            <option value="{{ form.busname.value|default_if_none:'' }}">예약 버스 1번</option>  
                            <option value="{{ form.busname.value|default_if_none:'' }}">예약 버스 2번</option>  
                            <option value="{{ form.busname.value|default_if_none:'' }}">예약 버스 3번</option>   
                        </select>
                    </div> 
                    <div class="form-group">
                        <label for="startStation">출발지</label> 
                        <input type="text" class="form-control" name="startStation" id="startStation"
                            value="{{ form.startStation.value|default_if_none:' ' }}"> 
                    </div> 
                    <div class="form-group">
                        <label for="endStation">도착지</label>
                        <input type="text" class="form-control" name="endStation" id="endStation" 
                            value="{{ form.endStation.value|default_if_none:' ' }}"> 
                    </div> 
                    <button type="submit" class="btn btn-primary">버스 선택하기</button>
                </form>
            </div>
        </div>
    </section>

    </div>

    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy;2022 대구를 빛내는 SW해커톤 by.밥친구들</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
</body>
</html>

templates/bus_seat.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>달려라 달구벌</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="../static/assets/css/main.css" />
		<noscript><link rel="stylesheet" href="../static/assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">

        <div id="wrapper">
            <!-- Header -->
					<header id="header" class="alt">
						<a href="main.html" class="logo"><strong> 달려라 달구벌 </strong> <span>by 밥친구들</span></a>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

		    <!-- Menu -->
					<nav id="menu">
						<ul class="links">
							<li><a href="/">Home</a></li>
							<li><a href="landing.html">버스 정보 조회</a></li>
							<li><a href="/reserve">예약버스 예약</a></li>
							<li><a href="elements.html">저상버스 예약</a></li>
						</ul>
						<ul class="actions stacked">
							<li><a href="/view_reservation" class="button primary fit">예약 조회</a></li>
							<li><a href="#" class="button fit">도움말</a></li>
						</ul>
					</nav>
        <!-- Banner -->
				<!-- Note: The "styleN" class below should match that of the header element. -->
					<section id="banner" class="style2">
						<div class="inner">
							<span class="image">
								<img src="../static/images/pic02.jpg" alt="" /><!-- 이미지 넣기  -->
							</span>
							<header class="major">
								<h1>버스 예약 시스템</h1>
							</header>
							<div class="content">
								<p>좌석 선택</p>
							</div>
						</div>
					</section>

        <!-- Main -->
		<div id="main" class="alt">
            <section id="one">
                <div class="inner">
                    <img src="../static/images/ReserveBus_Seat.jpg" alt="" />
                    <br/>
                    <br/>
                    <br/>
                    <h2>좌석 선택</h2>
                        <form method="post" action="/bus_select_check">
                            <div class="fields">
                                <div class="field half">
                                    <!-- 좌석 번호 선택하는거 -->
                                    <select name="seat_name" id="seat_name">
                                        {% for index in range(0,26) %}
                                            {% if seat_list[index] == True %}
                                            <option value="{{ index+1 }}">{{ index+1 }}</option>
                                            {% endif %}
                                        {% endfor %}
            <!--  여기에 좌석번호 --></select><br/>
                                </div>
                                <div class="field half">
                                    <button type="submit" class="button">좌석 예약하기</button>
                                </div>
                            </div>
                        </form>
                </div>
            </section>
        </div>

        <!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<ul class="icons">
						<li><a href="https://github.com/sosschs9/Hackathon_2022" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; 밥친구들</li><li>Design: <a href="https://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</footer>
        </div>

        <!-- Scripts -->
			<script src="../static/assets/js/jquery.min.js"></script>
			<script src="../static/assets/js/jquery.scrolly.min.js"></script>
			<script src="../static/assets/js/jquery.scrollex.min.js"></script>
			<script src="../static/assets/js/browser.min.js"></script>
			<script src="../static/assets/js/breakpoints.min.js"></script>
			<script src="../static/assets/js/util.js"></script>
			<script src="../static/assets/js/main.js"></script>
    </body>
</html>